<a href="https://colab.research.google.com/github/Abhay182005dat/Numpy-and-Pandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Numpy



In [2]:
import numpy as np

###Basics

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# Get Dimension
print(a.ndim)
b.ndim

1


2

In [6]:
# Get shape
b.shape

(2, 4)

In [7]:
# Get data type
print(a.dtype)
print(b.dtype)
a = np.array([1,2,3] , dtype = 'int16')

print(a.dtype)

int64
int64
int16


In [8]:
a.itemsize # gives the size in bytes i.e for a = 16 the 16/8 = 2

2

In [9]:
# Get total size
a.nbytes # a.size * a.itemsize where a.size is the total number of elements

6

###Accessing / Changing  specific elements ,rows,columns etc

In [10]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
a.shape

(2, 7)

In [12]:
# Get a specific element
print(a[0][1])
print(a[1,1])
print(a[1,0])
print(a[1,-1])

2
9
8
14


In [13]:
# Get a specific row
print(a[0]) # or a[0,:]
print(a[1])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [14]:
# Get specific columns
print(a[:,1]) # all the rows but only specific columns
print(a[:,0])

[2 9]
[1 8]


In [15]:
print(a[0 , 1:6:2]) # startindex:endindex:step  1,2,3,4,5,6

[2 4 6]


In [16]:
print(a)
a[:,2] = [5]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [17]:
# 3-D example
b = np.array([[[1,2],[3,4]] , [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
print(b.shape)
print(b.ndim)

(2, 2, 2)
3


In [19]:
# get specific element
print(b[0,1,1])
print(b[:,1,:])
print(b[:,0,:])

4
[[3 4]
 [7 8]]
[[1 2]
 [5 6]]


In [20]:
# replace
print(b[:,1,:],"\n")
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[3 4]
 [7 8]] 

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing different types of arrays

In [21]:
# ALL 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# ALL 1's Matrix
np.ones((4,3,2) , dtype = 'int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [24]:
np.full((2,2) , 99 , dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [27]:
# Make a matrix like other one full_like
np.full_like(a,4) #or a.shape

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
# Random Decimal numbers
np.random.rand(4,2)

array([[0.07026931, 0.45029134],
       [0.93297905, 0.1869314 ],
       [0.66421579, 0.42262113],
       [0.6097792 , 0.78146563]])

In [29]:
np.random.random_sample(a.shape)

array([[0.45401686, 0.35385258, 0.67376817, 0.04307856, 0.49315678,
        0.20644337, 0.03673227],
       [0.6371583 , 0.19788686, 0.30665703, 0.82411022, 0.32692824,
        0.23804413, 0.07249434]])

In [ ]:
# Random Integer Values