<a href="https://colab.research.google.com/github/Abhay182005dat/Numpy-and-Pandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Numpy



In [1]:
import numpy as np

###Basics

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
# Get Dimension
print(a.ndim)
b.ndim

1


2

In [5]:
# Get shape
b.shape

(2, 4)

In [6]:
# Get data type
print(a.dtype)
print(b.dtype)
a = np.array([1,2,3] , dtype = 'int16')

print(a.dtype)

int64
int64
int16


In [7]:
a.itemsize # gives the size in bytes i.e for a = 16 the 16/8 = 2

2

In [8]:
# Get total size
a.nbytes # a.size * a.itemsize where a.size is the total number of elements

6

###Accessing / Changing  specific elements ,rows,columns etc

In [9]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
a.shape

(2, 7)

In [11]:
# Get a specific element
print(a[0][1])
print(a[1,1])
print(a[1,0])
print(a[1,-1])

2
9
8
14


In [12]:
# Get a specific row
print(a[0]) # or a[0,:]
print(a[1])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [13]:
# Get specific columns
print(a[:,1]) # all the rows but only specific columns
print(a[:,0])

[2 9]
[1 8]


In [14]:
print(a[0 , 1:6:2]) # startindex:endindex:step  1,2,3,4,5,6

[2 4 6]


In [15]:
print(a)
a[:,2] = [5]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [16]:
# 3-D example
b = np.array([[[1,2],[3,4]] , [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
print(b.shape)
print(b.ndim)

(2, 2, 2)
3


In [18]:
# get specific element
print(b[0,1,1])
print(b[:,1,:])
print(b[:,0,:])

4
[[3 4]
 [7 8]]
[[1 2]
 [5 6]]


In [19]:
# replace
print(b[:,1,:],"\n")
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[3 4]
 [7 8]] 

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing different types of arrays

In [20]:
# ALL 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
# ALL 1's Matrix
np.ones((4,3,2) , dtype = 'int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [22]:
np.full((2,2) , 99 , dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [23]:
# Make a matrix like other one full_like
np.full_like(a,4) #or a.shape

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
# Random Decimal numbers
np.random.rand(4,2)

array([[0.9355653 , 0.75202044],
       [0.60255981, 0.53729889],
       [0.81762723, 0.86765478],
       [0.50825247, 0.38465567]])

In [25]:
np.random.random_sample(a.shape)

array([[0.55921342, 0.07110126, 0.41305372, 0.42468209, 0.35412685,
        0.87339373, 0.35871573],
       [0.20262284, 0.93009416, 0.39492019, 0.87964652, 0.74285335,
        0.84250459, 0.67250405]])

In [26]:
# Random Integer Values
print(np.random.randint(7))
print(np.random.randint(7,size = (3,3))) # 7 is the end number
print('\n')
print(np.random.randint(-4,2 , size = (3,3)))

5
[[3 4 0]
 [4 4 1]
 [0 6 3]]


[[-3 -3  0]
 [-2 -2  1]
 [-1 -3  0]]


In [27]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3)
print(r1,'\n')
r1 = np.repeat(arr,3,axis = 0) # It repeats the 0th axis which is [1,2,3]
print(r1)

[1 1 1 2 2 2 3 3 3] 

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
ans = np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])
ans

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [30]:
ans1 = np.ones((5,5))
ans1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
ans2 = np.zeros((3,3),dtype = 'int16' )
ans2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [32]:
ans2[1,1] = 9
ans2

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int16)

In [33]:
ans1[1:4,1:4] = ans2 # 1st row to 3rd row and then 1st column to 3rd column

In [34]:
ans1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

####Be Careful while copying

In [35]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a) # now  a is also modified

[100   2   3]
[100   2   3]


#### Mathematics

In [36]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [37]:
a+=2
a

array([3, 4, 5, 6])

In [38]:
a-2

array([1, 2, 3, 4])

In [39]:
a*2

array([ 6,  8, 10, 12])

In [40]:
a**2

array([ 9, 16, 25, 36])

In [41]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

#### Linear Algebra


In [42]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [43]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [44]:
stats = np.array([[1,2,3],[4,5,6]])

In [45]:
np.min(stats)

1

In [46]:
np.min(stats,axis = 0) # Row wise

array([1, 2, 3])

In [47]:
np.min(stats,axis = 1) # Column wise

array([1, 4])

In [48]:
np.max(stats)

6

In [49]:
np.sum(stats)

21

In [50]:
np.sum(stats , axis = 0)

array([5, 7, 9])

In [51]:
np.sum(stats , axis = 1)

array([ 6, 15])

#### Reorganizing Arrays

In [52]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [53]:
after = before.reshape(8,1)
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [54]:
after = before.reshape(2,2,2)
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
# Vertically Stacking arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

####Miscellaneous

In [59]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [61]:
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

####Boolean Masking

In [62]:
filedata >50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [63]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [72]:
#You can index  with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8])
a[[1,2,7]]

array([2, 3, 8])

In [77]:
np.any(filedata > 50 , axis = 0) #check the three numbers of every row

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [82]:
np.any(filedata > 50 , axis = 1) # Checks if any value in each row of 'filedata' is > 50. Returns True/False for each row.

array([ True,  True,  True])

In [84]:
filedata[((filedata>50) & (filedata <100))]

array([75, 75, 55, 78, 76, 88], dtype=int32)